'scope: extension':
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - 'src/extension/**'
              - 'esbuild.config.mjs'
              - 'esbuild.test-electron.config.mjs'
              - 'tsconfig.json'
              - '.vscodeignore'
              - 'package-lock.json'
              - 'package.json'

'scope: client':
  - all:
      - changed-files:
          - any-glob-to-any-file:
              - 'src/client/**'
              - 'scripts/build-rel-client.sh'
              - 'Cargo.lock'
              - 'Cargo.toml'
