'scope: extension':
  - all:
      - changed-files:
          - AnyGlobToAnyFile:
              - 'src/extension/**'
              - 'esbuild.config.mjs'
              - 'esbuild.test-electron.config.mjs'
              - 'tsconfig.json'
              - '.vscodeignore'
              - 'package-lock.json'
              - 'package.json'

'scope: client':
  - all:
      - changed-files:
          - AnyGlobToAnyFile:
              - 'src/client/**'
              - 'Cargo.lock'
              - 'Cargo.toml'
