name: 'relabel by changed files'
on:
  - pull_request_target

jobs:
  relabel:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: label-scope-by-changed-files
        uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
