name: test_client
on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '!v*'

jobs:
  cargo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check:
          - id: clippy
            subcmd: clippy --quiet --all-features -- -Dwarnings --target=x86_64-unknown-linux-musl
          - id: test_debug
            subcmd: test --quiet --target=x86_64-unknown-linux-musl
          - id: test_release
            subcmd: test --quiet --target=x86_64-unknown-linux-musl --release

    steps:
      - uses: actions/checkout@v4

      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{  matrix.check.id }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests inside Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/hankei6km/h6-dev-containers
          imageTag: 2022-12-01-main-cli_rust
          push: never
          subFolder: .devcontainer/cli
          runCmd: |
            cargo ${{ matrix.check.subcmd }}

  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cli-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm キャッシュファイルは Linux/macOS の「~/.npm」に保存される
          path: ~/.npm
          key: ${{ runner.os }}-cli-npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cli-npm-${{ env.cache-name }}-
            ${{ runner.os }}-cli-npm-

      - name: Run tests inside Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/hankei6km/h6-dev-containers
          imageTag: 2022-12-01-main-cli_rust
          push: never
          subFolder: .devcontainer/cli
          # パスの指定方法はあとで考える
          runCmd: |
            cd ../../
            npm ci
            bash src/client/test/scripts/test_cli.sh
